## Install required plugins if not already installed

required_plugins = %w(

  vagrant-librarian-puppet
)
plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

## Create modules directory if not exists

Dir.mkdir("./puppet/modules") unless Dir.exists?("./puppet/modules")

## Vagrant configuration

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.hostname = 'projektzespolowy.box'
  config.vm.network "private_network", ip: '10.0.0.10'
	config.vm.network :forwarded_port, guest: 3306, host: 3309
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "./..", "/home/vagrant/ProjektZespolowy"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 2
    vb.name = "ProjektZespolowyDev"
  end
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
	config.vm.provision :shell, :path => "db.sh"  
	config.vm.provision 'shell', :inline => <<-SHELL
    apt-get update
    apt-get install -y puppet
  SHELL
  config.librarian_puppet.puppetfile_dir = 'puppet'
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = './puppet/manifests'
    puppet.module_path = './puppet/modules'
    puppet.hiera_config_path = './puppet/hiera.yaml'
    puppet.options = '--verbose'
  end
end
