--cwiczenia
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Zginanie przedramion w podporze tylem na laweczkach',1,'Dlonie ulozone na brzegu jednej laweczki, stopy oparte na drugiej laweczce, cialo zawieszone w powietrzu: - wziac wdech i zgiac przedramiona, po czym wyprostowac je (odepchnac sie na nich); - wykonac wydech w koncowej fazie cwiczenia. Cwiczenie to angazuje miesien trojglwy ramienia, miesnie piersiowe i przednioa czesc miesni naramiennych. Na udach mozna polozyc ciezarek, dzieki czemu odpychanie bedzie trudniejsze, a wysilek intensywniejszy');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Pull-over ze sztanga w pozycji lezacej na poziomej laweczce',1,'Ramiona wyciagniete do gory, sztanga trzymana nachwytem (uchwyt gryfu na szerokosci rozstawu barkow): - wziac wdech, nabierajac do pluc maksymalnie duzo powietrza i opuscic sztange za glowe, lekko zginajac konczyny gorne w lokciach; - wykonac wydecg, powracajac do pozycji wyjsciowej.  Cwiczenie to rozwija miesien piersiowy wiekszy najszerszy grzbietu, jak rowniez miesnie zebate przednie, miesien rownolegloboczny i miesien piersiowy mniejszy. Wykonuje sie je z niewielkim obciazeniem.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Zginanie ramion na poreczach (DIPSY / SZWEDZKIE POMPKI)',1,'Ramiona wyprostowane, oparte na poreczach, konczyny dolne zwisaja nie dotykajac podloza:  - wziac wdech i zgiac calkowicie przedramiona tak, aby piersi znalazly sie na wysokosci poreczy;  - wykonac wydech w koncowej fazie pracy.  Im glebsze pochylenie tulowia do przodu tym pelniejsze zaangazowanie miesni piersiowych (ich czesci wewnetrznej), i na odwrot, im bardziej wyprostowany tulow  tym pelniejsza praca miesni trojglowych ramienia.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Naprzemianstronne unoszenie ramion w bok z wykorzystaniem wyciagu dolnego',1,'Raczka wyciagu w dloni, ramie wzdluz tulowia: - wziac wdech i uniesc ramie do poziomu; - wykonac wydech w koncowej fazie ruchu. Cwiczenie to rozwija miesien naramienny, glownie jego czesc srodkowa wielopierzasta, tzn. zbudowana z kilku pasm w ksztalcie piora, dlatego nalezy zmieniac katy, pod jakimi unosi sie ramiona w celu zaangazowania wszystkich pasm miesnia.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Pompki (zginanie ramion w podporze przodem)',1,'Rece wyprostowanie oparte o podloze, rozstawione na szerokosc barkow (lub szerzej), stopy przy sobie lub w lekkim rozwarciu: - wziac wdech i zgiac ramiona tak, aby klatka piersiowa znalazla sie przy podlodze, nie wyginajac nadmiernie grzbietu w okolicach ledzwiowych; - wykonac wydech w koncowej fazie ruchu. Jest to doskonale cwiczenie na miesien piersiowy wiekszy i miesien trojglwy ramienia. Mozna he wykonywac w dowolnym miejscu.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Podciaganie sztangielki w kleku podpartym na laweczce',1,'Sztangielka trzymana w jednej rece w polnawroceniu, druga reka i zgieta w kolanie konczyna dolna oparte na laweczce; - zablokowac grzbiet, wziac wdech i podciagnac sztangielke najwyzej, jak to mozliwe, trzymajac ramie przy tulowiu i odwodzac mocno lokiec do tylu; - wyonac wydech w koncowej fazie ruchu. W celu uzyskania maksymalnego napiecia miesni mozna lekko skrecic klatke pirsiowa w koncowej fazie podciagania. Cwiczenie to angazuje glownie miesien najszerszy grzbietu, miesien obly wiekszy, tylne czesci miesnia naramiennego oraz miesien czworoboczny i miesien rownolegloboczny ( w koncowej fazie napiecia) a ponadto miesnie zginacze ramion (dwugllwy ramienia, ramienny i ramienno-promienowy).');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Unoszenie kolan na przyrzadzie do cwiczen na miesnie brzucha',2,'W oparciu na lokciach, grzbiet zablokowany: - wziac wdech i podciagnac kolana do piersi, wygiac grzbiet w luk, aby napiac miesnie tloczni brzusznej;  - wykonac wydech w koncowej fazie ruchu. Cwiczenie to angazuje miesnie zginacze biodra, glownie miesnie biodrowo-ledzwiowe, jak rowniez miesnie skosne i miesien prosty brzucha, przy czym ten ostatni jest angazowany intensywnie w swej dolnej czesci');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Unoszenie ramion ze sztangielkami w pozycji lezacej na boku',2,'W pozycji lezacej na boku na podlodze lub laweczce, sztangielka trzymana nachwytem: - wziac wdech i podniesc ramie do poziomu;  wykonac wydech w koncowej fazie ruchu. W odroznieniu do podnoszenia ramion w pozycji stojacej, ktore angazuja stopniowo miesien naramienny az do osiagniecia maksymalnej intensywnosci wysilku w koncowej fazie (kiedy ramiona dochodza do poziomu), w tym cwiczeniu wysilek koncentruje sie w poczatkowej fazie podnoszenia. Najlepsze wyniki uzyskuje sie, wykonujac 10-20 powtorzen.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Prostowanie przedramion ze sztanga w pozycji lezacej na laweczce',2,'W pozycji lezacej na plecach na laweczce, sztanga trzymana nachwytem, ramiona ustawione pionowo w stosunku do laweczki: - wziac wdech i zgiac przedramiona, starajac sie nie odwodzic zanadto w bok lokci przy opuszczaniu sztangi na wysokosc czola - wykonac wydech w koncowej fazie ruchu.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Wyciskanie sztangielek w pozycji lezacej',2,'W pozycji lezacej na poziomej laweczce, stopy wsparte na podlozu, konczyny gorne ugiete w lokciach, sztangielki trzymane nachwytem na wysokosci piersi:  - wziac wdech i wyprostowac konczyny gorne w pionie, obracajac jednoczesnie przedramiona tak, aby dlonie znalazly sie naprzeciwko siebie; - gdy dlonie znajda sie naprzeciwko siebie, wykonac skurcz izometryczny w celu skoncentrowania wysilku w czesci mostkowo-zebrowej miesi piersiowych wiekszych - wykonac wydech w koncowej fazie ruchu. Cwiczenie to przypomina wyciskanie sztangi, ale ze wzgledu na wieksza amplitude ruchu sprzyja ono rozciaganiu miesni piersiowych wiekszych. Podczas wykonywania tego cwiczenia pracuje rowniez miesien trojglowy i przednie czesci miesnia naramiennego.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Unoszenie konczyn dolnych na skosnej laweczce ze zgieciem kregoslupa i uniesieniem miednicy',2,'W pozycji lezacej na skosnej laweczce, rece na barierce lub drazku: - uniesc konczyny dolne do pionu, nastepniepodniesc miednice, zgiac kregoslup i probujac dotknac kolanami glowy. Cwiczenie to angazuje przy podnoszeniu konczyn miesien biodrowo-ledzwiowy, miesien napinacz powiezi szerokiej i miesien prosty uda ( czesc miesnia czworoglowego uda) Podczas zginania kregoslupa angazowana jest tlocznia brzuszna, glownie czesc podpepkowa miesni prostych brzucha.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Rozpietki ze sztangielkami w pozycji lezacej',3,'W pozycji lezacej na waskiej laweczce umozliwiajacej wykonywanie swobodnych ruchow ramionami, sztangielki trzymane w rekach wyciagnietych w gore lub lekko zgietych w lokciach w celu odciazenia stawow:  - wykonac wdech a nastepnie rozlozyc ramiona do poziomu;  - powrocic do pionu, wykonujac wydech;  - wykonac niewielki skurcz izometryczny w koncowej fazie ruchu w celu wzmocnienia pracy mostkowo-zebrowej czesci miesni piersiowych wiekszych. Tego cwiczenia nigdy nie wykonuje sie z duzymi obciazeniami. Koncentruje ono wysilek glownie w miesniach piersiowych wiekszych. Jest to podstawowe cwiczenie rozwijajace miesnie klatki piersiowej ktore zwieksza takze objetosc pluc i swietnie uelastycznia miesnie.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Unoszenie tulowia z podloza',3,'W pozycji lezacej, konczyny dolne ugiete, stopy na podlodze, rece za glowa: - wziac wdech i uniesc tulow, wyginajac kregoslup w luk, wykonac wydech w koncowej fazie cwiczenia; - powrocic do pozycji wyjsciowej ale tym razem nie kladac sie calkiem na podlodze; - ponownie uniesc tulow ( w okolicy brzucha powinno pojawic sie pieczenie) Cwiczenie to angazuje miesnie zginacze biodra oraz miesnie skosne brzucha, ale przede wszystkim miesnien prosty brzucha.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Sklony tulowia w przod w pozycji lezacej (CRUNCH)',3,'W pozycji lezacej, rece za glowa, uda ustawione pionowo do podloza, kolana ugiete: - wziac wdech i oderwac ramiona od podloza, przyciagajac kolana do glowy i zginajac kregoslup; - wykonac wdech w koncowej fazie ruchu. Cwiczenie to angazuje glownie miesien prosty brzucha. Aby bardziej intensywnie pracowaly miesnie skosne brzucha, wystarczy zgiac kregoslup i przyciagnac naprzemiennie prawy lokiec do lewego kolana i lewy lokiec do prawego kolana.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Prostowanie przedramion ze sztangielkami w pozycji lezacej',3,'W pozycji lezacej, sztangielki trzymane w obu rekach, ramiona ustawione pionowo do podloza: - wziac wdech i zgiac przedramiona, kontrolujac ruch; - powrocic do pozycji wyjsciowej i wykonac wydech w koncowej fazie ruchu. Cwiczenie to rownomiernie angazuje wszystkie trzy glowy miesnia trojglowego ramienia.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Prostowanie konczyn dolnych z wykorzystaniem przyrzadu',3,'W pozycji siedzacej na przyrzadzie, rece zacisniete na drazkach lub siedzeniu, aby utrzymac tulow nieruchomo, konczyny dolne zgiete w kolanach, a w okolicach kostek ulozone sa walki;  - wziac wdech i wyprostowac konczyny tak aby ustawic je do poziomu; - wykonac wydech w koncowej fazie ruchu. Jesto do doskonale cwiczenie izolowane na miesnie czworoglowe. Nalezy zauwazyc ze im bardziej pochyli sie oparcie tym wieksze bedzie tylopochylenie miednicy. Rozciaga sie mocniej miesnien prosty uda, ktory jest dwustawowa czescia srodkowa miesnia czworoglowego, dzieki czemu bedzie on intensywiej pracowal podczas prostowania konczyn dolnych.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Wyciskanie sztangi na skosnej laweczce (glowa do gory)',3,'W pozycji siedzacej na skosnej laweczce (nachylenie laweczki w granicach 45 i 60 stopni), sztanga trzymana nachwytem na szerokosci wiekszej niz rozstaw barkow: - wziac wdech i przeniesc sztange w okolice wciecia szyjnego mostka; - wyciskac, wykonujac wydech w koncowej fazie ruchu. Cwiczenie to angazuje miesien piersiowy wiekszy, glownie jego czesc obojczykowa i przednia czesc miesnia naramiennego, miesien trojglowy ramienia, miesnien zebaty przedni i miesien piersiowy mniejszy. Mozna je wykonywac przy wykorzystaniu stojakow.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Wyciskanie sztangielek w pozycji siedzacej',3,'W pozycji siedzacej na laweczce, sztangielki trzymane nachwytem (kciuki do wewnatrz) na wysokosci barkow: wziac wdech i wyciskac sztangielki az do wyprostawania ramion w pionie; - wykonac wydech w koncowej fazie ruchu. Cwiczenie to angazuje miesien naramienny, glownie jego czesc srodkowa, jak rowniez miesien czworoboczny, miesien zebaty przedni i miesien trojglowy ramienia. Cwiczenie to mozna tez wykonac w pozycji stojacej lub prostujac ramiona na przemian.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Naprzemianstronne zginanie przedramion ze sztangielkami z obrotem nadgarstka i uniesieniem lokci',4,'W pozycji siedzacej sztangielki trzymane w obu rekach nachwytem, przedramiona w ustawieniu posrednim: wziac wdech i zgiac przedramie, wykonujac polobrot nadgarstka na zewnatrz, zanim przedramie znajdzie sie w polozeniu poziomym;  - zakonczyc ruch podniesieniem lokci i wykonac wydech. Cwiczenie to angazuje miesien ramienno-promieniowy, miesien ramienny, miesien dwuglowy ramienia, miesien naramienny czesc przednia a w mniejszym zakresie miesien kruczo-ramienny i czesc obojczykowa miesnia piersiowego wiekszego.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Wspiecie na palcach w pozycji siedzacej na przyrzadzie (cwiczenie na miesnie plaszczkowate)',4,'W pozycji siedzacej, dolna czesc ud pod wyscirlanym klockiem, palce stop na podstawce, piety lekko opuszczone: - wspiac sie na palcach (zgiecie podeszwowe) Cwiczenie to angazuje glownie miesien plaszczkowaty. Miesien ten ma przyczep u gory, pod stawem kolanowym, na kosci piszczelowej i strzalkowej i jest przymocowany do kosci pietowej przez sciegno Achillesa, jego podstawowa funkcja to prostowanie w stawie skokowym.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Wyciskanie sztangi zza karku',4,'W pozycji siedzacej, sztanga za karkiem trzymana nachwytem: - wziac wdech i wycisnac sztange pionowo, nie wyginajac nadmiernie grzbietu;  wykonac wykonac wydech w koncowej fazie ruchu. Cwiczenie to angazuje miesien naramienny, glownie jego czesc srodkowa i tylna, jak rowniez miesnien czworoboczny, miesien trojglowy ramienia i miesien zebaty przedni. W wyciskaniu uczestnicza rowniez, ale w mniejszym stopniu, miesnie rownolegloboczne, miesien podgrzebieniowy, miesien obly mniejszy, a w warstwie glebokiej miesien nadgrzbietowy.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Przyciaganie drazka wyciagu gornego do karku',4,'W pozycji siedzacej, twarza do przyrzadu, uda przytrzymywane przez walki, drazek trzymany nachwytem szeroko rozstawionymi rekami:  - wziac wdech i przyciagnac drazek za kark, odwodzac lokcie wzdluz tulowia; - wykonac wydechw  koncowej fazie ruchu. Jest to doskonale cwiczenie na zwiekszenie szerokosci miesni grzbietu. Angazuje miesnie najszersze grzbietu (glownie ich wlokna zewnetrzne i dolne) i miesnie oble wieksze. Angazowane sa rowniez miesnie zginacze przedramion (dwuglowy ramienia, ramienny i ramienno-promieniowy), jak rowniez miesnie rownolegloboczne i czesc wstepujaca miesni czworobocznych  przy czym te dwa ostatnie wlaczja sie w czasie sciagania lopatek. Jest to dobre cwiczenie dla poczatkujacych.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Naprzemianstronne zginanie przedramion ze sztangielkami (lokiec wsparty na udzie)',4,'W pozycji siedzacej, lokiec wsparty na wewnetrznej stronie uda: - wziac wdech i zgiac przedramie:  -w koncowej fazie ruchu wykonac wydech. To izolowane cwiczenie pozwala na kontrole zakresu, szybkosci i dokladnosci ruchu. Angazuje glownie miesien dwuglowy ramienia i miesien ramienny.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Cwiczenie na miesien dwuglowy ramienia z wykorzystaniem wyciagu gornego',4,'W pozycji stojacej centralnie w stosunku do wyciagu, ramiona wyciagniete, raczki wyciagu trzymane podchwytem: - wziac wdech i zgiac przedramiona; - wykonac wydeh w koncowej fazie ruchu. Cwiczenie to, ktore najczesciej konczy trening miesni ramion, pozwala na rozwijanie miesnia dwuglowego ramienia, glownie jego glowy krotkiej uprzednio rozciagnietej i napinanej w pozycji rozlozenia ramion; rozwija rowniez miesien ramienny bedacy jednostawowym zginaczem lokcia. Cwiczenia tego nie wykonuje sie nigdy przy duzym obciazeniu. Istotne, aby skoncentrowac sie na odczuciu kurczenia sie wewnetrznej czesci miesnia dwuglowego ramienia. Najlepsze wyniki przynosza dlugie serie cwiczen.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Naprzemianstronne zginanie przedramion ze sztangielkami trzymanymi neutralnie',5,'W pozycji stojacej lub siedzacej, sztangielki trzymane w obu rekach nachwytem, przedramie w pozycji posredniej - wziac wdech i zgiac oba przedramiona rownoczesnie lub naprzemiennie - wykonac wydech w koncowej fazie ruchu. To cwiczenie najlepiej rozwija miesien ramienno-promieniowy. Wplywa ono rozniez na miesien dwuglowy ramienia i miesien ramienny oraz w mniejszym stopniu na miesien prostownik promieniowy krotki nadgarstka i miesien prostownik promieniowy dlugi nadgarstka.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Cwiczenie na miesien trojglowy ramienia z wykorzystaniem wyciagu gornego (raczka wyciagu trzymana podchwytem)',5,'W pozycji stojacej przodem do przyrzadu, ramiona wzdluz tulowia, zgiete w lokciach, rece na raczkach przyrzadu: - wziac wdech i wyprostowac przedramiona, starajac sie nie odrtwac lokci od tulowia; - wykonac wydech w koncowej fazie ruchu. Pozycja nachwytu nie pozwala na trening z duzymi obciazeniami, dlatego cwiczenia to wykonuje sie z niewielkim obciazeniem w celu rozwijania miesnia trojglowego ramienia i skoncentrowania wysilku w glowie przysrodkowej miesnia trojglowego ramienia. Ruch prostowania przedramion angazuje rowniez miesien lokciowy i miesnie prostowniki nadgarstkow. Te ostatnie miesnie (prostownik lokciowy nadgarstka, prostownik palcow, prostownik palca malego, prostownik promieniowy dlugi nadgarstka i prostownik promieniowy krotki nadgarstka) usztywniaja nadgarstek dzieki skurczowi izometrycznemu trwajacemu przez caly czas wykonywania ruchu prostowania przedramion.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Naprzemienne prostowanie przedramion z wykorzystaniem wyciagu gornego (raczka wyciagu trzymana podchwytem)',5,'W pozycji stojacej twarza do przyrzadu, raczka wyciagu trzymana podchwytem: - wziac wdech i wyprostowac przedramie; - wykonac wydech. To cwiczenie angazuje miesien trojglowy ramienia, glownie jego glowe boczna.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Zginanie przedramion ze sztanga trzymana podchwytem',5,'W pozycji stojacej, grzbiet wyprostowany, sztanga trzymana podchwytem (rece rozstawione na szerokosc nieco wieksza niz rozstaw barkow); - wziac wdech a nastepnie zgiac przedramiona, starajac sie nie poruszac klatka piersiowa przez wykonanie izometrycznego skurczu miesni posladkowych, brzusznych i przykregoslupowych;  wykonac wdech w koncowej fazie ruchu. Cwiczenie to angazuje glownie miesien dwuglowy ramienia i miesien ramienny, a w mniejszym stopniu miesien ramienny-promienowy, miesien nawrotny obly i wszystkie miesnie zginacze nadgarstka i palcow.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Cwiczenie na miesnie kulszowo-goleniowe w pozycji stojacej z wykorzystaniem przyrzadu',5,'W pozycji stojacej, klatka piersiowa oparta o podstawke, kolana zablokowane, konczyny dolne wyprostowane, pod kostkami walki: - wziac wdech i zgiac kolano; - wykonac wydech w koncowej fazie ruchu. Cwiczenie to angazuje wszystkie miesnie kulszowo-goleniowe (miesnie polsciegniste i polbloniaste, glowe krotka i dluga miesnia dwuglowego uda), a w mniejszym stopniu miesnie brzuchate lydki. Aby mocniej zaangazowac te ostatnie miesnie w wykonywanie ruchu, wystarczy podczas zginania kolana zgiac stope, aby zaangazowaz slabiej (do czego zwykle sie dazy) nalezy stope wyprostowac');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Naprzemianstronne unoszenie ramion w przod ze sztangielkami',5,'W pozycji stojacej, konczyny dolne w lekim rozkroku, sztangielki trzymane nachwytem spoczywaja na udzue lub nieco z boku: - wziac wdech i unosic naprzemiennie ramiona do przodu na wysokosci oczu; - wykonac wydech w koncowej fazie ruchu. Cwiczenie to angazuje glownie przednia czesc miesni naramiennych, czesc obojczykowa miesnia piersiowego wiekszego, a w mniejszym stopiniu reszte miesnia naramiennego. We wszystkich ruchach podnozenia ramion biora udzual miesnie przytwierdzajace lopatke do klatki piersiowej, takie jak miesien zebaty przedni i miesien rownolegloboczny wiekszy, pozwalajac kosci ramiennej balansowac na stabilnym wsporniku.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Podciaganie pionowe sztangi do brody (waski uchwyt)',6,'W pozycji stojacej, konczyny dolne w lekkim rozkroku, grzbiet mocno wyprostowany, sztanga trzymana nachwytem (rece rozstawione na szerokosc dloni lub troche wieksza): - wziac wdech, podciagnac sztange wzdluz tulowia do brody, podnoszac lokcie mozliwie najwyzej; - wykonac wydech i kontrolowac opuszczanie sztangi tak, aby bylo ono plynne. Cwiczenie to angazuje miesnie czworoboczne, glownie ich czesc zstepujaca, jak rowniez miesnie naramianne, miesnie dzwigacze lopatki, miesnie dwuglowe ramienia, miesnie ramienne, miesnie przedramion, brzucha i posladkow oraz miesnie krzyzowo-ledzwiowe.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Unoszenie ramion w bok ze sztangielkami',6,'W pozycji stojacej, konczyny dolne w lekkim rozkroku, grzbiet wyprostowany, ramiona ulozone wzdluz tulowia, sztangielki w rekach: - podniesc ramiona do poziomu (lokcie lekko zgiete); - powrocic do pozycji wyjsiowej. Cwiczenie to angazuje miesnie naramienne, glownie ich czesc srodkowa. Cwiczenia tego nie wykonuje sie nigdy z duzymi obciazeniami. Najlepsze rezultaty daja serie 10-25 powtorzen wykonywane pod roznymi katami, bez zbyt dlugich odpoczynkow miedzy seriami i kontynuowane do chwili, gdy odczuje sie pieczenie. W celu zwiekszenia intensywnosci wysilku mozna miedzy poszczegolnymi seriami przez kilka sekund trzymac uniesione poziomo ramiona w skurczu izometrycznym.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Polprzysiad ze sztangielkami',6,'W pozycji stojacej, konczyny dolne w lekkim rozkroku, sztangielki trzymane w rekach, ramiona opadaja swobodnie: - patrzec prosto przed siebie, wziac wdech, lekko wygiac grzbiet i zgiac kolana;  kiedy uda znajda sie w poziomie do podloza, wyprostowac konczyny dolne i powrocic do pozycji wyjsciowej; - wykonac wydech. Cwiczenie to angazuje glownie miesnie czworoglowe uda i miesnie posladkowe.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Wspiecie na palcach jednej konczyny dolnej ze sztangielka',6,'W pozycji stojacej, palce stopy wsparte o podstawke, sztangielka w jednej rece, druga reka dla lepszej rownowagi oparta na wsporniku: - wspiac sie na palcach (zgiecie podeszwowe), utrzymujac staw kolanowy w wyproscie lub w lekkim zgieciu; - powrocic do pozycji wyjsciowej. Cwiczenie to angazuje miesien trojglowy lydki (zbudowany z miesnia plaszczkowatego, glowy przysrodkowej i glowy bocznej miesnia brzuchatego lydki. Przy kazdym powtorzeniu nalezy wykonac pelne zgiecie, aby dobrze rozciagnac miesien trojglowy lydki. Tylko wykonywanie dlugich serii cwiczen daje najlepsze rezultaty');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Wniosy barkow ze sztanga (SZRUGSY)',6,'W pozycji stojacej, przodem do polozonej na podlozy lub podstawce sztangi, konczyny dolne w lekkim rozkroku: - chwycic sztange rekami w nawroceniu lub uchwytem odwroconym, jesli obciazenia sa duze (uchwyt nie czerszy niz rozstaw barkow)  - mocno wyprostowac grzbiet, napiac miesnie brzucha i wykonac wznos ramion. Cwiczenie to roziwja partie zstepujaca miesnia czworobocznego, glownie jego czesc potyliczno-obojczykowa, jak rozniez okolice kata lopatki.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Cwiczenie na miesien trojglowy ramienia z wykorzystaniem wyciagu gornego (raczka wyciagu trzymana nachwytem)',6,'W pozycji stojacej, rece na raczce przyrzadu, lokcie wzdluz tulowia: - wziac wdech i wyprostowac przedramiona, starajac sie nie odrywac lokci od tulowia; - wykonac wydech w koncowej fazie cwiczenia');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Naprzemianstronne zginanie przedramion z wykorzystaniem wyciagu dolnego',7,'W pozycji stojacej, twarza do przodu, raczka wyciagu trzymana podchwytem: - wziac wdech i zgiac przedramie; - wykonac wydech w koncowej fazie ruchu. Cwiczenie to pozawala na koncentracje wysilku w obrebie miesnia dwuglowego ramienia i sprzyja intensywnemu ukrwieniu miesnia.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Sklony tulowia w przod z wykorzystaniem wyciagu gornego',7,'W siadzie klecznym, drazek za karkiem:  wziac wdech i zgiac kregoslup, zblizajac mostek do kosci loniowej; wykonac wydech w koncowej fazie ruchu. Cwiczenie tego nigdy nie wykonuje sie z duzym obciazeniami. Nalezy skuic sie na pracy miesni, aby lepiej zlokalizowac wysilek w tloczni brzusznej a glownie w miesniu prostym brzucha.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Wypychanie ciezaru na suwnicy (uda w pochyleniu)',7,'W ulozeniu na przyrzadzie, grzbiet przylega do oparcia, stopy rozstawione niezbyt szeroko: - wziac wdech, odblokowac zabezpieczenie przyrzadu i najmocniej jak to mozliwe zgiac kolana tak, aby konczyny dolne znalazly sie przy klatce piersiowej; - powrocic do pozycji wyjsciowej wykonujac wydech w koncowej fazie ruchu. Jesli stopy ulozone sa w dolnej czesci platformy,pracuja przede wszystkim miesnie czworogloweud,gdy natomiast stopy znajduja sie w gornej czesci platformy wysilek koncentruje sie bardziej na miesniach posladkowych i kulszowo-goleniowych. Jesli stopy sa szeroko rozstawione, wysilek kierowany jest na miesnie przywodziciele.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Podciaganie na drazku umocowanym na stale',7,'W zwisie na drazku, rece w nawroceniu, rozstawione szeroko: - wziac wdech i podciagnac sie tak aby klatka piersiowa znalazla sie prawie na wysokosci drazka;  - wykonac wydech w koncowej fazie ruchu  -powrocic do pozycji wyjsciowej kontrolujac ruch podczas opadania a nastepnie powtorzyc cale cwiczenie. To doskonale, choc wymagajace dosc duzej sily, cwiczenie rozwija miesien najszerszy grzebitu i miesien obly wiekszy, a w czsie sciagania lopatek w koncowej fazie podciagania takze miesnie rownolegloboczne oraz poprzeczne i wstepujace czesci miesnia czworobocznego. Angazuje rowniez miesien dwuglowy ramienai, miesien ramienny i miesien ramienno-promieniowy.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Podciaganie na drazku trzymanym podchwytem',7,'W zwisie na drazku, rece w odwroceniu, rozstawione na szerokosc barkow:  - wziac wdech, wypiac klatke piersiowa i podciagnac sie tak aby broda znalazla sie na wysokosci drazka; - wykonac wydech w koncowej fazie ruchu. Cwiczenie to rozwija miesien najszerszy grzbietu i miesien obly wiekszy raz umozliwia intensywny trening miesnia dwuglowego ramienia i miesnia ramiennego. Z tego wzgledu moze zostac wlaczone do planu treningu ramion. W cwiczeniu bierze rowniez udzial miesien czworoboczny (jego czesc poprzeczna i wstepujaca), miesien rownolegloboczny i miesnie piersiowe.');
insert into zesp.exercise (exercise_name,id_part_description,description) values ('Unoszenie konczyn dolnych na zwisie na drazku',7,'W zwisie na drazku: - wziac wdech i uniesc kolana mozliwie najwyzej, starajac sie zblizyc kosc loniowa do mostka przez zgiecie kregoslupa ; - wykonac wydech w koncowej fazie cwiczenia. Cwiczenie to oddzialuje na miesnie biodrowo-ledzwiowe, miesien prosty uda i misien napinacz powiezi szerokiej (podczas unoszenia konczyn dolnych). W celu zlokalizowania pracy w tloczni brzusznej zaleca sie wykonywanie niewielkich poziomych ruchow udami. Kolana nie moga jednak nigdy opadac ponizej poziomu.');

--partie
insert into zesp.body_part (description) values ('biceps');
insert into zesp.body_part (description) values ('triceps');
insert into zesp.body_part (description) values ('barki');
insert into zesp.body_part (description) values ('klatka');
insert into zesp.body_part (description) values ('plecy');
insert into zesp.body_part (description) values ('nogi');
insert into zesp.body_part (description) values ('brzuch');






